AIRPORTS = [
    {
        "airport_code": "DAL",
        "airport_name": "Dallas Love Field",
        "city": "Dallas",
        "state": "Texas",
        "country": "USA",
        "timezone": "America/Chicago",
    },
    {
        "airport_code": "DEN",
        "airport_name": "Denver International Airport",
        "city": "Denver",
        "state": "Colorado",
        "country": "USA",
        "timezone": "America/Denver",
    },
    {
        "airport_code": "HOU",
        "airport_name": "William P. Hobby Airport",
        "city": "Houston",
        "state": "Texas",
        "country": "USA",
        "timezone": "America/Chicago",
    },
    {
        "airport_code": "PHX",
        "airport_name": "Phoenix Sky Harbor International Airport",
        "city": "Phoenix",
        "state": "Arizona",
        "country": "USA",
        "timezone": "America/Phoenix",
    },
    {
        "airport_code": "LAS",
        "airport_name": "Harry Reid International Airport",
        "city": "Las Vegas",
        "state": "Nevada",
        "country": "USA",
        "timezone": "America/Los_Angeles",
    },
    {
        "airport_code": "MDW",
        "airport_name": "Chicago Midway International Airport",
        "city": "Chicago",
        "state": "Illinois",
        "country": "USA",
        "timezone": "America/Chicago",
    },
    {
        "airport_code": "BWI",
        "airport_name": "Baltimore/Washington International Airport",
        "city": "Baltimore",
        "state": "Maryland",
        "country": "USA",
        "timezone": "America/New_York",
    },
]
