FLIGHTS = [
    {
        "flight_number": "WN210",
        "origin": "DAL",
        "destination": "DEN",
        "scheduled_departure": "08:00",
        "scheduled_arrival": "09:45",
        "aircraft_type": "Boeing 737-800",
        "active_flag": True,
    },
    {
        "flight_number": "WN211",
        "origin": "DAL",
        "destination": "LAS",
        "scheduled_departure": "09:15",
        "scheduled_arrival": "10:35",
        "aircraft_type": "Boeing 737-700",
        "active_flag": True,
    },
    {
        "flight_number": "WN212",
        "origin": "HOU",
        "destination": "BWI",
        "scheduled_departure": "07:30",
        "scheduled_arrival": "11:20",
        "aircraft_type": "Boeing 737 MAX 8",
        "active_flag": True,
    },
    {
        "flight_number": "WN310",
        "origin": "PHX",
        "destination": "DEN",
        "scheduled_departure": "12:00",
        "scheduled_arrival": "14:05",
        "aircraft_type": "Boeing 737-800",
        "active_flag": True,
    },
    {
        "flight_number": "WN410",
        "origin": "LAS",
        "destination": "MDW",
        "scheduled_departure": "15:20",
        "scheduled_arrival": "20:45",
        "aircraft_type": "Boeing 737-700",
        "active_flag": True,
    },
    {
        "flight_number": "WN510",
        "origin": "MDW",
        "destination": "DAL",
        "scheduled_departure": "06:40",
        "scheduled_arrival": "09:05",
        "aircraft_type": "Boeing 737-800",
        "active_flag": True,
    },
    {
        "flight_number": "WN610",
        "origin": "BWI",
        "destination": "HOU",
        "scheduled_departure": "13:10",
        "scheduled_arrival": "15:35",
        "aircraft_type": "Boeing 737 MAX 8",
        "active_flag": True,
    },
]
